version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    # rsvg-convert for SVG -> PDF conversion
    # using Sphinx extension sphinxcontrib.rsvgconverter, see
    # https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter
    - librsvg2-bin
  jobs:
    post_checkout:
      - git fetch --unshallow || true
python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
    - requirements: doc/fallback_theme.txt
formats: all
sphinx:
  configuration: doc/conf.py