language: python
python:
  - "3.7"
matrix:
  include:

  # default Python + latest Sphinx + check for broken links
  - env: ADDITIONAL_COMMAND="python -m sphinx doc/ doc/_build/ -b linkcheck"

  # a few older Sphinx releases using default Python version
  - env: SPHINX="==1.7.0"
  - env: SPHINX="==1.7.9"
  - env: SPHINX="==1.8.0"
  - env: SPHINX="==1.8.5"
  - env: SPHINX="==2.0.0"
  - env: SPHINX="==2.1.0"
  - env: SPHINX="==2.1.2"

  # a few Python versions using latest Sphinx release
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "nightly"
  #- python: "pypy3"

addons:
  apt:
    packages:
      - pandoc
install:
  - pip install Sphinx$SPHINX
  - pip install .
  #- pip install -r doc/requirements.txt
  # Install manually until
  # https://github.com/mcmtroffaes/sphinxcontrib-bibtex/pull/178 is solved:
  - pip install ipykernel
  - pip install numpy
  - pip install matplotlib
  - pip install pandas
  - pip install sphinxcontrib-svg2pdfconverter
  - pip install git+https://github.com/mgeier/sphinxcontrib-bibtex.git@allow-older-sphinx

script:
  - python -m nbsphinx
  - python -m sphinx doc/ doc/_build/ -b html
  - python -m sphinx doc/ doc/_build/ -b latex
  - python -m sphinx doc/ doc/_build/ -b epub
  - $ADDITIONAL_COMMAND
