name: Check links in documentation
on: [push, pull_request]
env:
  PYTHONWARNINGS: error
  APT_INSTALL: sudo apt-get install -y --no-install-recommends
  PIP: python -m pip
  SPHINX: python -m sphinx -W --keep-going --color
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install pandoc
      run: |
        $APT_INSTALL pandoc
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Show Python version
      run: |
        python --version
    - name: Install Python package
      env:
        # DeprecationWarning: Unimplemented abstract methods {'locate_file'}
        # https://github.com/pypa/pip/issues/11684
        PYTHONWARNINGS: error,default::DeprecationWarning
      run: |
        $PIP install .
    - name: Install docs dependencies
      env:
        # DeprecationWarning: Unimplemented abstract methods {'locate_file'}
        # https://github.com/pypa/pip/issues/11684
        # silence warning from building sphinxcontrib-svg2pdfconverter
        PYTHONWARNINGS: default
      run: |
        $PIP install -r doc/requirements.txt
    - name: Check links
      env:
        # There is a weird warning from jupyter_core (https://github.com/jupyter/jupyter_core/issues/398)
        # RemovedInSphinx10Warning: 'sphinx.util.import_object' is deprecated
        # https://github.com/sphinx-doc/sphinx/issues/13083
        PYTHONWARNINGS: error,default::DeprecationWarning,default:'sphinx.util.import_object'
      run: |
        $SPHINX -d _doctrees/ doc/ _build/linkcheck/ -b linkcheck -q
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: ${{ success() || failure() }}
      with:
        name: linkcheck
        path: _build/linkcheck/output.*
